ALTER TABLE profiles
    ADD COLUMN deleted    BOOLEAN  NOT NULL DEFAULT FALSE,
    ADD COLUMN deleted_at DATETIME NULL;


ALTER TABLE addresses
    DROP COLUMN deleted,
    DROP COLUMN deleted_at,
    ADD COLUMN is_default BOOLEAN NOT NULL DEFAULT TRUE;