ALTER TABLE users
    ADD COLUMN suspended    BOOLEAN  NOT NULL DEFAULT FALSE,
    ADD COLUMN deleted      BOOLEAN  NOT NULL DEFAULT FALSE,
    ADD COLUMN suspended_at DATETIME NULL,
    ADD COLUMN deleted_at   DATETIME NULL;

ALTER TABLE profiles
    ADD COLUMN suspended    BOOLEAN  NOT NULL DEFAULT FALSE,
    ADD COLUMN suspended_at DATETIME NULL;

